<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <OutputType>Library</OutputType>
    <RootNamespace>ReClass.NET_Tests</RootNamespace>
    <AssemblyName>ReClass.NET_Tests</AssemblyName>
    <Platforms>x86;x64</Platforms>
    <Platform Condition="'$(Platform)' == '' Or '$(Platform)' == 'AnyCPU'">x86</Platform>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <OutputPath>$(SolutionRoot)bin\Tests\$(Configuration)\$(Platform)\</OutputPath>
    <NoWarn>$(NoWarn);xUnit1026;xUnit2013</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ReClass.NET\ReClass.NET.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="System.IO.Compression" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.11.1" />
    <PackageReference Include="Moq" Version="4.10.1" />
    <PackageReference Include="NFluent" Version="2.8.0" />
    <PackageReference Include="xunit" Version="2.9.2" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.8.2">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>

</Project>
